# Generated by Django 6.0.3 on 2026-06-14 21:51

import boxe.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome de quem vai usar a chave", max_length=100
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=boxe.models.generate_api_key,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expiration_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lutador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("nacionalidade", models.CharField(max_length=50)),
                ("peso", models.FloatField(help_text="Peso em kg")),
                ("categoria", models.CharField(max_length=50)),
                ("vitorias", models.IntegerField(default=0)),
                ("derrotas", models.IntegerField(default=0)),
                ("empates", models.IntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Combate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("rounds", models.IntegerField()),
                (
                    "metodo",
                    models.CharField(
                        help_text="KO, TKO, Decisão, Empate", max_length=50
                    ),
                ),
                (
                    "lutador1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combates_como_lutador1",
                        to="boxe.lutador",
                    ),
                ),
                (
                    "lutador2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combates_como_lutador2",
                        to="boxe.lutador",
                    ),
                ),
                (
                    "vencedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vitorias_combates",
                        to="boxe.lutador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Titulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "organizacao",
                    models.CharField(help_text="WBC, WBA, IBF, WBO", max_length=20),
                ),
                ("categoria", models.CharField(max_length=50)),
                (
                    "campeao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="titulos",
                        to="boxe.lutador",
                    ),
                ),
            ],
        ),
    ]
