# Generated by Django 6.0.5 on 2026-05-13 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("biografia", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, upload_to="docentes/")),
                ("link_lusofona", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=10)),
                ("instituicao", models.CharField(max_length=100)),
                ("ano_inicio", models.IntegerField()),
                ("descricao", models.TextField()),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField()),
                ("link_relatorio", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoTecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("acronimo", models.CharField(blank=True, max_length=10)),
                ("logo", models.ImageField(blank=True, upload_to="tecnologias/")),
                ("link_oficial", models.URLField(blank=True)),
                ("preferencia", models.IntegerField(default=1)),
                ("descricao", models.TextField(blank=True)),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tecnologias",
                        to="portfolio.tipotecnologia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=50)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                (
                    "docentes",
                    models.ManyToManyField(related_name="ucs", to="portfolio.docente"),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(blank=True, upload_to="projetos/")),
                ("ano", models.IntegerField()),
                ("github_link", models.URLField(blank=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
