# Generated by Django 6.0.3 on 2026-05-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licenciatura",
            old_name="duracao_anos",
            new_name="ano_inicio",
        ),
        migrations.RenameField(
            model_name="licenciatura",
            old_name="apresentacao",
            new_name="descricao",
        ),
        migrations.RemoveField(
            model_name="licenciatura",
            name="objetivos",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="imagem",
        ),
        migrations.AddField(
            model_name="docente",
            name="biografia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="docente",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="docentes/"),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="instituicao",
            field=models.CharField(default="Universidade Lusófona", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="link",
            field=models.URLField(
                default="[https://informatica.ulusofona.pt/ensino/licenciaturas/engenharia-informatica/](https://informatica.ulusofona.pt/ensino/licenciaturas/engenharia-informatica/)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="sigla",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="sigla",
            field=models.CharField(default="Universidade Lusófona", max_length=20),
            preserve_default=False,
        ),
    ]
